version: "3.8"

services:
  linux1:
    build: .
    ports:
      - "1201:22"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 50M
